In [2]:
# Loaded variable 'df' from URI: /Users/rodrigosouza/Documents/Python/AdidasvsNike/Adidas Vs Nike.csv
import pandas as pd
df = pd.read_csv(r'/Users/rodrigosouza/Documents/Python/AdidasvsNike/Adidas Vs Nike.csv')
df.head()

,Product Name,Product ID,Listing Price,Sale Price,Discount,Brand,Description,Rating,Reviews,Last Visited
0,Women's adidas Originals NMD_Racer Primeknit S...,AH2430,14999,7499,50,Adidas Adidas ORIGINALS,Channeling the streamlined look of an '80s rac...,4.8,41,2020-04-13T15:06:14
1,Women's adidas Originals Sleek Shoes,G27341,7599,3799,50,Adidas ORIGINALS,"A modern take on adidas sport heritage, tailor...",3.3,24,2020-04-13T15:06:15
2,Women's adidas Swim Puka Slippers,CM0081,999,599,40,Adidas CORE / NEO,These adidas Puka slippers for women's come wi...,2.6,37,2020-04-13T15:06:15
3,Women's adidas Sport Inspired Questar Ride Shoes,B44832,6999,3499,50,Adidas CORE / NEO,"Inspired by modern tech runners, these women's...",4.1,35,2020-04-13T15:06:15
4,Women's adidas Originals Taekwondo Shoes,D98205,7999,3999,50,Adidas ORIGINALS,This design is inspired by vintage Taekwondo s...,3.5,72,2020-04-13T15:06:15

In [3]:
df.describe

<bound method NDFrame.describe of                                            Product Name  Product ID  \
0     Women's adidas Originals NMD_Racer Primeknit S...      AH2430
1                  Women's adidas Originals Sleek Shoes      G27341
2                     Women's adidas Swim Puka Slippers      CM0081
3      Women's adidas Sport Inspired Questar Ride Shoes      B44832
4              Women's adidas Originals Taekwondo Shoes      D98205
...                                                 ...         ...
3263                                 Air Jordan 8 Retro  CI1236-100
3264                         Nike Phantom Venom Club IC  AO0578-717
3265               Nike Mercurial Superfly 7 Academy TF  AT7978-414
3266                                    Nike Air Max 98  AH6799-300
3267                                     Nike P-6000 SE  CJ9585-600

      Listing Price  Sale Price  Discount                    Brand  \
0             14999        7499        50  Adidas Adidas ORIGINALS
1              7599        3799        50         Adidas ORIGINALS
2               999         599        40        Adidas CORE / NEO
3              6999        3499        50        Adidas CORE / NEO
4              7999        3999        50         Adidas ORIGINALS
...             ...         ...       ...                      ...
3263          15995       12797         0                     Nike
3264           4995        3497         0                     Nike
3265           8495        5947         0                     Nike
3266              0       16995         0                     Nike
3267           8995        6297         0                     Nike

                                            Description  Rating  Reviews  \
0     Channeling the streamlined look of an '80s rac...     4.8       41
1     A modern take on adidas sport heritage, tailor...     3.3       24
2     These adidas Puka slippers for women's come wi...     2.6       37
3     Inspired by modern tech runners, these women's...     4.1       35
4     This design is inspired by vintage Taekwondo s...     3.5       72
...                                                 ...     ...      ...
3263  The Air Jordan 8 Retro recaptures the memorabl...     5.0        1
3264  The Nike Phantom Venom Club IC is engineered f...     0.0        0
3265  The soft upper of the Nike Mercurial Superfly ...     5.0        1
3266  The Nike Air Max 98 features the OG design lin...     4.0        4
3267  A mash-up of Pegasus' past, the Nike P-6000 SE...     0.0        0

             Last Visited
0     2020-04-13T15:06:14
1     2020-04-13T15:06:15
2     2020-04-13T15:06:15
3     2020-04-13T15:06:15
4     2020-04-13T15:06:15
...                   ...
3263  2020-04-13T15:41:01
3264  2020-04-13T15:41:03
3265  2020-04-13T15:41:07
3266  2020-04-13T15:41:19
3267  2020-04-13T15:42:57

[3268 rows x 10 columns]>

In [7]:
df.isna().sum()

Product Name     0
Product ID       0
Listing Price    0
Sale Price       0
Discount         0
Brand            0
Description      3
Rating           0
Reviews          0
Last Visited     0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.rename(columns = {'Product ID' : 'Id Produto', 'Product Name':'Nome Produto', 'Listing Price' : 'Lista de preço', 'Sale Price' : 'Preço Promocional', 'Discount' : 'Desconto',
                'Brand' : 'Marca', 'Description' : 'Dezscrição', 'Rating' : 'Avaliação', 'Reviews' : 'Análise', 'Last Visited' : 'Visita mais recente'})

df.head()

,Nome Produto,Id Produto,Lista de preço,Preço Promocional,Desconto,Marca,DEscrição,Avaliação,Análise,Visita mais recente
0,Women's adidas Originals NMD_Racer Primeknit S...,AH2430,14999,7499,50,Adidas Adidas ORIGINALS,Channeling the streamlined look of an '80s rac...,4.8,41,2020-04-13T15:06:14
1,Women's adidas Originals Sleek Shoes,G27341,7599,3799,50,Adidas ORIGINALS,"A modern take on adidas sport heritage, tailor...",3.3,24,2020-04-13T15:06:15
2,Women's adidas Swim Puka Slippers,CM0081,999,599,40,Adidas CORE / NEO,These adidas Puka slippers for women's come wi...,2.6,37,2020-04-13T15:06:15
3,Women's adidas Sport Inspired Questar Ride Shoes,B44832,6999,3499,50,Adidas CORE / NEO,"Inspired by modern tech runners, these women's...",4.1,35,2020-04-13T15:06:15
4,Women's adidas Originals Taekwondo Shoes,D98205,7999,3999,50,Adidas ORIGINALS,This design is inspired by vintage Taekwondo s...,3.5,72,2020-04-13T15:06:15

In [24]:
total_lista = df['Lista de preço'].sum()
total_desconto = df['Preço Promocional'].sum()

desconto = total_lista - total_desconto

print(f"Total sem desconto: R$ {total_lista:,.2f}")
print (f"Total com desconto: R$ {total_desconto:,.2f}")
print(f"Diferença final é: R$ {desconto:,.2f}")

Total sem desconto: R$ 22,444,690.00
Total com desconto: R$ 20,046,780.00
Diferença final é: R$ 2,397,910.00