In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
insonia = pd.read_csv('insonia_digital.csv')
insonia.head()

,user_id,age,gender,chronotype,occupation,bedtime_hour,screen_time_before_bed_min,primary_app_category,screen_brightness_pct,blue_light_filter_on,...,room_temperature_f,ambient_noise_db,sleep_onset_latency_min,total_sleep_hours,rem_sleep_pct,deep_sleep_pct,awakenings_count,sleep_efficiency_pct,next_day_fatigue_score,sleep_debt_category
0,1,32,Female,Intermediate,Student,23.94,102,Social Media,100,False,...,73.5,32.6,60.3,5.67,15.2,13.5,11,63.7,8.85,Moderate
1,2,26,Female,Intermediate,Student,0.06,14,Short-Form Video,87,True,...,66.8,44.3,24.5,7.42,16.9,22.3,1,92.9,2.98,No Debt
2,3,34,Male,Night Owl,Professional,1.48,58,Messaging,76,True,...,68.0,45.6,21.9,6.98,20.2,18.5,2,84.6,3.90,Mild
3,4,43,Female,Intermediate,Professional,22.42,48,Social Media,56,False,...,72.3,42.3,34.5,7.67,14.4,17.3,6,79.9,4.81,No Debt
4,5,25,Male,Early Bird,Professional,22.43,29,Streaming,96,True,...,80.1,10.0,37.4,6.31,16.6,16.1,0,89.3,3.88,Mild

In [7]:
insonia.isnull().sum()

user_id                       0
age                           0
gender                        0
chronotype                    0
occupation                    0
bedtime_hour                  0
screen_time_before_bed_min    0
primary_app_category          0
screen_brightness_pct         0
blue_light_filter_on          0
caffeine_intake_mg            0
caffeine_last_hour            0
physical_activity_min         0
room_temperature_f            0
ambient_noise_db              0
sleep_onset_latency_min       0
total_sleep_hours             0
rem_sleep_pct                 0
deep_sleep_pct                0
awakenings_count              0
sleep_efficiency_pct          0
next_day_fatigue_score        0
sleep_debt_category           0
dtype: int64

In [9]:
insonia.info()

<class 'pandas.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   user_id                     8500 non-null   int64
 1   age                         8500 non-null   int64
 2   gender                      8500 non-null   str
 3   chronotype                  8500 non-null   str
 4   occupation                  8500 non-null   str
 5   bedtime_hour                8500 non-null   float64
 6   screen_time_before_bed_min  8500 non-null   int64
 7   primary_app_category        8500 non-null   str
 8   screen_brightness_pct       8500 non-null   int64
 9   blue_light_filter_on        8500 non-null   bool
 10  caffeine_intake_mg          8500 non-null   int64
 11  caffeine_last_hour          8500 non-null   float64
 12  physical_activity_min       8500 non-null   int64
 13  room_temperature_f          8500 non-null   float64
 14  ambient_noise_db            8500 non-null   float64
 15  sleep_onset_latency_min     8500 non-null   float64
 16  total_sleep_hours           8500 non-null   float64
 17  rem_sleep_pct               8500 non-null   float64
 18  deep_sleep_pct              8500 non-null   float64
 19  awakenings_count            8500 non-null   int64
 20  sleep_efficiency_pct        8500 non-null   float64
 21  next_day_fatigue_score      8500 non-null   float64
 22  sleep_debt_category         8500 non-null   str
dtypes: bool(1), float64(10), int64(7), str(5)
memory usage: 1.8 MB

In [12]:
import pandas as pd

# 1. Carrega o arquivo (lembre-se de ajustar o caminho se necessário)
insonia = pd.read_csv('insonia_digital.csv')

# 2. Dicionário de mapeamento (Nome Antigo: Nome Novo)
colunas_traduzidas = {
    'user_id': 'id_usuario',
    'age': 'idade',
    'gender': 'genero',
    'chronotype': 'cronotipo',
    'occupation': 'profissao',
    'bedtime_hour': 'hora_ir_cama',
    'screen_time_before_bed_min': 'tempo_tela_antes_dormir_min',
    'primary_app_category': 'categoria_app_principal',
    'screen_brightness_pct': 'brilho_tela_pct',
    'blue_light_filter_on': 'filtro_luz_azul_ativo',
    'caffeine_intake_mg': 'consumo_cafeina_mg',
    'caffeine_last_hour': 'hora_ultimo_consumo_cafeina',
    'physical_activity_min': 'atividade_fisica_min',
    'room_temperature_f': 'temperatura_quarto_f',
    'ambient_noise_db': 'ruido_ambiente_db',
    'sleep_onset_latency_min': 'latencia_inicio_sono_min',
    'total_sleep_hours': 'total_horas_sono',
    'rem_sleep_pct': 'sono_rem_pct',
    'deep_sleep_pct': 'sono_profundo_pct',
    'awakenings_count': 'quantidade_despertares'
}

insonia.rename(columns=colunas_traduzidas, inplace=True)
insonia.head()

,id_usuario,idade,genero,cronotipo,profissao,hora_ir_cama,tempo_tela_antes_dormir_min,categoria_app_principal,brilho_tela_pct,filtro_luz_azul_ativo,...,temperatura_quarto_f,ruido_ambiente_db,latencia_inicio_sono_min,total_horas_sono,sono_rem_pct,sono_profundo_pct,quantidade_despertares,sleep_efficiency_pct,next_day_fatigue_score,sleep_debt_category
0,1,32,Female,Intermediate,Student,23.94,102,Social Media,100,False,...,73.5,32.6,60.3,5.67,15.2,13.5,11,63.7,8.85,Moderate
1,2,26,Female,Intermediate,Student,0.06,14,Short-Form Video,87,True,...,66.8,44.3,24.5,7.42,16.9,22.3,1,92.9,2.98,No Debt
2,3,34,Male,Night Owl,Professional,1.48,58,Messaging,76,True,...,68.0,45.6,21.9,6.98,20.2,18.5,2,84.6,3.90,Mild
3,4,43,Female,Intermediate,Professional,22.42,48,Social Media,56,False,...,72.3,42.3,34.5,7.67,14.4,17.3,6,79.9,4.81,No Debt
4,5,25,Male,Early Bird,Professional,22.43,29,Streaming,96,True,...,80.1,10.0,37.4,6.31,16.6,16.1,0,89.3,3.88,Mild