In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

# Load the dataset
df = pd.read_csv("data.csv")
df.head()

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4

In [49]:
df.rename(columns={'Student_ID': 'ID_Estudante', 'Academic_Level' : 'Nivel_Academico',  'Age': 'Idade', 'Gender': 'Genero', 'Daily_Usage_Hours': 'Horas_Uso_Diario','Weekend_Extra_Hours': 'Horas_Uso_Fim_Semana', 'Primary_Platform': 'Plataforma_Principal', 'Device_Type': 'Tipo_Dispositivo', 'Sleep_Duration_Hours': 'Duracao_Sono_Horas', 'Sleep_Quality_Score': 'Qualidade_Sono'}, inplace=True)   
df.head()

,ID_Estudante,Idade,Genero,Nivel_Academico,Plataforma_Principal,Horas_Uso_Diario,Horas_Uso_Fim_Semana,Tipo_Dispositivo,Duracao_Sono_Horas,Qualidade_Sono
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID_Estudante          4500 non-null   str
 1   Idade                 4500 non-null   int64
 2   Genero                4500 non-null   str
 3   Nivel_Academico       4500 non-null   str
 4   Plataforma_Principal  4500 non-null   str
 5   Horas_Uso_Diario      4500 non-null   float64
 6   Horas_Uso_Fim_Semana  4500 non-null   float64
 7   Tipo_Dispositivo      4500 non-null   str
 8   Duracao_Sono_Horas    4500 non-null   float64
 9   Qualidade_Sono        4500 non-null   int64
dtypes: float64(3), int64(2), str(5)
memory usage: 554.3 KB

In [51]:
df.isnull().sum()

ID_Estudante            0
Idade                   0
Genero                  0
Nivel_Academico         0
Plataforma_Principal    0
Horas_Uso_Diario        0
Horas_Uso_Fim_Semana    0
Tipo_Dispositivo        0
Duracao_Sono_Horas      0
Qualidade_Sono          0
dtype: int64

In [52]:
df.describe()

,Idade,Horas_Uso_Diario,Horas_Uso_Fim_Semana,Duracao_Sono_Horas,Qualidade_Sono
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000
std,1.981182,2.604497,0.699245,1.189998,1.030484
min,15.000000,0.900000,0.000000,3.000000,1.000000
25%,17.000000,3.400000,1.300000,6.000000,2.000000
50%,19.000000,4.700000,1.800000,6.800000,3.000000
75%,20.000000,6.600000,2.300000,7.500000,3.000000
max,26.000000,14.000000,4.500000,10.500000,5.000000

In [53]:
data = df.groupby(['Genero', 'Plataforma_Principal', 'Tipo_Dispositivo'])['Idade'].mean().reset_index()
print(data)

               Genero Plataforma_Principal Tipo_Dispositivo      Idade
0              Female            Instagram        Laptop/PC  18.757576
1              Female            Instagram       Smartphone  18.703764
2              Female            Instagram           Tablet  18.600000
3              Female             LinkedIn        Laptop/PC  19.800000
4              Female             LinkedIn       Smartphone  18.851064
..                ...                  ...              ...        ...
61  Prefer not to say               TikTok           Tablet  19.000000
62  Prefer not to say          X (Twitter)       Smartphone  18.000000
63  Prefer not to say              YouTube        Laptop/PC  19.000000
64  Prefer not to say              YouTube       Smartphone  18.833333
65  Prefer not to say              YouTube           Tablet  17.000000

[66 rows x 4 columns]

In [48]:
# Quantidade de estudantes por gênero e plataforma
uso_por_genero = (
    df.groupby(['Genero', 'Plataforma_Principal'])
      .size()
      .reset_index(name='Quantidade por Genero')
      .sort_values('Quantidade por Genero', ascending=False)
)
display(uso_por_genero)

# Dispositivo mais usado para acessar cada plataforma
uso_dispositivo = (
    df.groupby(['Plataforma_Principal', 'Tipo_Dispositivo'])
      .size()
      .reset_index(name='Quantidade')
      .sort_values('Quantidade', ascending=False)
      .drop_duplicates('Plataforma_Principal')
      .sort_values('Quantidade', ascending=False)
)
display(uso_dispositivo)

# Médias de idade e tempo de uso por plataforma
medias_por_plataforma = (
    df.groupby('Plataforma_Principal')
      .agg(
          Media_Idade=('Idade', 'mean'),
          Media_Horas_Diarias=('Horas_Uso_Diario', 'mean'),
          Media_Horas_Fim_de_Semana=('Horas_Uso_Fim_Semana', 'mean')
      )
      .sort_values('Media_Horas_Diarias', ascending=False)
      .round(2)
      .reset_index()
)
display(medias_por_plataforma)

               Genero Plataforma_Principal  Quantidade por Genero
0              Female            Instagram                    730
7                Male            Instagram                    642
4              Female               TikTok                    607
11               Male               TikTok                    570
6              Female              YouTube                    401
13               Male              YouTube                    385
3              Female             Snapchat                    228
10               Male             Snapchat                    216
2              Female               Reddit                    108
9                Male               Reddit                    107
5              Female          X (Twitter)                    106
12               Male          X (Twitter)                     91
1              Female             LinkedIn                     54
14         Non-Binary            Instagram                     45
8                Male             LinkedIn                     40
20  Prefer not to say            Instagram                     36
17         Non-Binary               TikTok                     29
24  Prefer not to say               TikTok                     20
16         Non-Binary             Snapchat                     20
19         Non-Binary              YouTube                     17
26  Prefer not to say              YouTube                     15
23  Prefer not to say             Snapchat                      8
15         Non-Binary               Reddit                      8
22  Prefer not to say               Reddit                      6
25  Prefer not to say          X (Twitter)                      6
18         Non-Binary          X (Twitter)                      3
21  Prefer not to say             LinkedIn                      2

   Plataforma_Principal Tipo_Dispositivo  Quantidade
1             Instagram       Smartphone        1219
13               TikTok       Smartphone        1019
19              YouTube       Smartphone         688
10             Snapchat       Smartphone         405
7                Reddit       Smartphone         187
16          X (Twitter)       Smartphone         176
4              LinkedIn       Smartphone          81

,Plataforma_Principal,Media_Idade,Media_Horas_Diarias,Media_Horas_Fim_de_Semana
0,Snapchat,18.63,5.46,1.77
1,TikTok,18.75,5.33,1.80
2,Reddit,18.58,5.31,1.88
3,LinkedIn,18.99,5.27,1.74
4,Instagram,18.72,5.26,1.79
5,YouTube,18.62,5.25,1.80
6,X (Twitter),18.85,5.14,1.84