In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt

impacto = pd.read_csv("impacto.csv")
impacto.head()

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04

In [9]:
impacto.info()

<class 'pandas.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student_ID                 16000 non-null  str
 1   Age                        16000 non-null  int64
 2   Gender                     16000 non-null  str
 3   Education_Level            16000 non-null  str
 4   Daily_Social_Media_Hours   16000 non-null  float64
 5   Daily_AI_Tool_Usage_Hours  16000 non-null  float64
 6   Sleep_Hours                16000 non-null  float64
 7   Physical_Activity_Hours    16000 non-null  float64
 8   Mental_Health_Score        16000 non-null  float64
 9   Physical_Health_Score      16000 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 1.6 MB

In [10]:
impacto.isnull().sum()

Student_ID                   0
Age                          0
Gender                       0
Education_Level              0
Daily_Social_Media_Hours     0
Daily_AI_Tool_Usage_Hours    0
Sleep_Hours                  0
Physical_Activity_Hours      0
Mental_Health_Score          0
Physical_Health_Score        0
dtype: int64

In [23]:
impacto = impacto.rename(columns={'Student_ID': 'Estudande_ID', 'Age': 'Idade', 'Gender':'Genero',
                                      'Education_Level':'Nivel de Educação', 'Daily_Social_Media_Hours':'Horas de Mídia Social', 
                                      'Daily_AI_Tool_Usage_Hours':'Média de Uso de Ferramentas de IA', 'Sleep_Hours' : 'Horas de Sono',
                                      'Physical_Activity_Hours' : 'Horas de Atividade Física', 'Mental_Health_Score':'Pontuação de Saúde Mental',
                                      'Physical_Health_Score': 'Pontuação de Saúde Física'})
impacto.head()

,Estudande_ID,Idade,Genero,Nive de Educação,Horas de Mídia Social,Média de Uso de Ferramentas de IA,Horas de Sono,Horas de Atividade Física,Pontuação de Saúde Mental,Pontuação de Saúde Física
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04

In [18]:
impacto.describe()

,Idade,Horas de Mídia Social,Média de Uso de Ferramentas de IA,Horas de Sono,Horas de Atividade Física,Pontuação de Saúde Mental,Pontuação de Saúde Física
count,16000.00000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000
mean,19.03875,4.541791,2.590624,6.545371,1.248359,72.493193,88.020465
std,3.76527,2.403044,1.679376,1.270515,1.038632,9.244818,9.691037
min,13.00000,0.000000,0.000000,2.000000,0.000000,32.560000,48.030000
25%,16.00000,2.840000,1.310000,5.680000,0.310000,66.760000,81.517500
50%,19.00000,4.500000,2.520000,6.540000,1.130000,73.750000,89.455000
75%,22.00000,6.180000,3.750000,7.410000,1.960000,79.550000,97.170000
max,25.00000,14.000000,9.500000,11.150000,5.000000,91.760000,99.980000

In [34]:
# Agrupa apenas por 'Genero' e calcula a média das colunas numéricas de interesse
impacto_agrupado = impacto.groupby('Genero')[
    ['Média de Uso de Ferramentas de IA', 'Horas de Mídia Social', 'Horas de Sono']
].mean().reset_index()

impacto_agrupado = impacto.groupby(['Genero', 'Idade'])[
    ['Média de Uso de Ferramentas de IA', 'Horas de Mídia Social', 'Horas de Sono']
].mean().reset_index()

impacto_agrupado = impacto.groupby('Genero').mean(numeric_only=True).reset_index()

display(impacto_agrupado)

,Genero,Idade,Horas de Mídia Social,Média de Uso de Ferramentas de IA,Horas de Sono,Horas de Atividade Física,Pontuação de Saúde Mental,Pontuação de Saúde Física
0,Female,19.005637,4.550783,2.613769,6.549368,1.242479,72.535110,87.936658
1,Male,19.070506,4.535594,2.568441,6.547228,1.253537,72.481782,88.130382
2,Non-binary,19.049363,4.508997,2.583025,6.473933,1.255924,72.124761,87.683010